In [1]:
import pandas as pd
from pathlib import Path

In [2]:
shark_attack_to_load = Path("global-shark-attack.xlsx")
shark_data = pd.read_excel(shark_attack_to_load)
shark_data

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number,Case Number.1,original order
0,NaN,1,Unprovoked,AUSTRALIA,New South Wales,Bondi,NaN,male,M,NaN,...,N,NaN,NaN,Waverly Library,5BC-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5BC-Australia,5BC,131.0
1,NaN,1000,Unprovoked,USA,Puerto Rico,Archeological site,NaN,male,M,29,...,N,NaN,Tiger shark,P. Seigel,1000AD-PuertoRico.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1000.00.00,1000.00.00,133.0
2,NaN,1500,Unprovoked,MEXICO,NaN,NaN,NaN,male,M,NaN,...,N,NaN,NaN,J. Castro,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200.00.00,1200.00.00,134.0
3,NaN,1518,Unprovoked,MEXICO,Yucatan,Cozumel,Swmming,A cacique (a chief),M,NaN,...,N,NaN,NaN,"C. Moore, GSAF",1518.04.00.R.chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R,1518.04.00.R,135.0
4,NaN,1543,Unprovoked,VENEZUELA,Magarita or Cubagua Islands,NaN,Pearl diving,Indian slave,M,NaN,...,Y,NaN,NaN,J. Castro,1543.00.00.R-LasCasas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1543.00.00,1543.00.00,136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6185,2023-08-16,2023,Provoked,PORTUGAL,Norte,9 nm off Vila do Conde,Fishing,male,M,35,...,N,19h30,Blue shark,"Portugese Resident, 8/17/2023",NaN,NaN,NaN,NaN,NaN,NaN
6186,2023-08-16,2023,Unprovoked,SPAIN,Valencia,Rabdells Beach,Wading,male,M,NaN,...,N,Afternoon,Blue shark,Las Provincias,NaN,NaN,NaN,NaN,NaN,NaN
6187,NaN,2023,Unprovoked,NEW CALEDONIA,South Province,"Chateau Royal Beach, Noumea",Swimming,Brigitte Soulard,M,49,...,N,10h30,Bull shark,"Les Nouvelles Caledoinnie, 1/30/2023",NaN,NaN,NaN,NaN,NaN,NaN
6188,NaN,2023,Unprovoked,USA,Florida,"Outer Mole, Fort Zachrry Tatlor Historic Park,...",Swimming,Nicolae Cioban,M,34,...,N,14h00,NaN,"Miami Herald, 1/14/2023",NaN,NaN,NaN,NaN,NaN,NaN
6189,1836-08-19,1836,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,NaN,...,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,230.0

In [3]:
#cleaning NaN in Sex column
shark_data = shark_data.dropna(subset=['Sex'])
shark_data

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number,Case Number.1,original order
0,NaN,1,Unprovoked,AUSTRALIA,New South Wales,Bondi,NaN,male,M,NaN,...,N,NaN,NaN,Waverly Library,5BC-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5BC-Australia,5BC,131.0
1,NaN,1000,Unprovoked,USA,Puerto Rico,Archeological site,NaN,male,M,29,...,N,NaN,Tiger shark,P. Seigel,1000AD-PuertoRico.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1000.00.00,1000.00.00,133.0
2,NaN,1500,Unprovoked,MEXICO,NaN,NaN,NaN,male,M,NaN,...,N,NaN,NaN,J. Castro,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200.00.00,1200.00.00,134.0
3,NaN,1518,Unprovoked,MEXICO,Yucatan,Cozumel,Swmming,A cacique (a chief),M,NaN,...,N,NaN,NaN,"C. Moore, GSAF",1518.04.00.R.chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R,1518.04.00.R,135.0
4,NaN,1543,Unprovoked,VENEZUELA,Magarita or Cubagua Islands,NaN,Pearl diving,Indian slave,M,NaN,...,Y,NaN,NaN,J. Castro,1543.00.00.R-LasCasas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1543.00.00,1543.00.00,136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6185,2023-08-16,2023,Provoked,PORTUGAL,Norte,9 nm off Vila do Conde,Fishing,male,M,35,...,N,19h30,Blue shark,"Portugese Resident, 8/17/2023",NaN,NaN,NaN,NaN,NaN,NaN
6186,2023-08-16,2023,Unprovoked,SPAIN,Valencia,Rabdells Beach,Wading,male,M,NaN,...,N,Afternoon,Blue shark,Las Provincias,NaN,NaN,NaN,NaN,NaN,NaN
6187,NaN,2023,Unprovoked,NEW CALEDONIA,South Province,"Chateau Royal Beach, Noumea",Swimming,Brigitte Soulard,M,49,...,N,10h30,Bull shark,"Les Nouvelles Caledoinnie, 1/30/2023",NaN,NaN,NaN,NaN,NaN,NaN
6188,NaN,2023,Unprovoked,USA,Florida,"Outer Mole, Fort Zachrry Tatlor Historic Park,...",Swimming,Nicolae Cioban,M,34,...,N,14h00,NaN,"Miami Herald, 1/14/2023",NaN,NaN,NaN,NaN,NaN,NaN
6189,1836-08-19,1836,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,NaN,...,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,230.0

In [4]:
#cleaning NaN in Country column
shark_data = shark_data.dropna(subset=['Country'])
shark_data

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number,Case Number.1,original order
0,NaN,1,Unprovoked,AUSTRALIA,New South Wales,Bondi,NaN,male,M,NaN,...,N,NaN,NaN,Waverly Library,5BC-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5BC-Australia,5BC,131.0
1,NaN,1000,Unprovoked,USA,Puerto Rico,Archeological site,NaN,male,M,29,...,N,NaN,Tiger shark,P. Seigel,1000AD-PuertoRico.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1000.00.00,1000.00.00,133.0
2,NaN,1500,Unprovoked,MEXICO,NaN,NaN,NaN,male,M,NaN,...,N,NaN,NaN,J. Castro,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200.00.00,1200.00.00,134.0
3,NaN,1518,Unprovoked,MEXICO,Yucatan,Cozumel,Swmming,A cacique (a chief),M,NaN,...,N,NaN,NaN,"C. Moore, GSAF",1518.04.00.R.chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R,1518.04.00.R,135.0
4,NaN,1543,Unprovoked,VENEZUELA,Magarita or Cubagua Islands,NaN,Pearl diving,Indian slave,M,NaN,...,Y,NaN,NaN,J. Castro,1543.00.00.R-LasCasas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1543.00.00,1543.00.00,136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6185,2023-08-16,2023,Provoked,PORTUGAL,Norte,9 nm off Vila do Conde,Fishing,male,M,35,...,N,19h30,Blue shark,"Portugese Resident, 8/17/2023",NaN,NaN,NaN,NaN,NaN,NaN
6186,2023-08-16,2023,Unprovoked,SPAIN,Valencia,Rabdells Beach,Wading,male,M,NaN,...,N,Afternoon,Blue shark,Las Provincias,NaN,NaN,NaN,NaN,NaN,NaN
6187,NaN,2023,Unprovoked,NEW CALEDONIA,South Province,"Chateau Royal Beach, Noumea",Swimming,Brigitte Soulard,M,49,...,N,10h30,Bull shark,"Les Nouvelles Caledoinnie, 1/30/2023",NaN,NaN,NaN,NaN,NaN,NaN
6188,NaN,2023,Unprovoked,USA,Florida,"Outer Mole, Fort Zachrry Tatlor Historic Park,...",Swimming,Nicolae Cioban,M,34,...,N,14h00,NaN,"Miami Herald, 1/14/2023",NaN,NaN,NaN,NaN,NaN,NaN
6189,1836-08-19,1836,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,NaN,...,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,230.0

In [5]:
#cleaning NaN in Fatal (Y/N) column
shark_data = shark_data.dropna(subset=['Fatal (Y/N)'])
shark_data

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number,Case Number.1,original order
0,NaN,1,Unprovoked,AUSTRALIA,New South Wales,Bondi,NaN,male,M,NaN,...,N,NaN,NaN,Waverly Library,5BC-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5BC-Australia,5BC,131.0
1,NaN,1000,Unprovoked,USA,Puerto Rico,Archeological site,NaN,male,M,29,...,N,NaN,Tiger shark,P. Seigel,1000AD-PuertoRico.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1000.00.00,1000.00.00,133.0
2,NaN,1500,Unprovoked,MEXICO,NaN,NaN,NaN,male,M,NaN,...,N,NaN,NaN,J. Castro,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200.00.00,1200.00.00,134.0
3,NaN,1518,Unprovoked,MEXICO,Yucatan,Cozumel,Swmming,A cacique (a chief),M,NaN,...,N,NaN,NaN,"C. Moore, GSAF",1518.04.00.R.chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R,1518.04.00.R,135.0
4,NaN,1543,Unprovoked,VENEZUELA,Magarita or Cubagua Islands,NaN,Pearl diving,Indian slave,M,NaN,...,Y,NaN,NaN,J. Castro,1543.00.00.R-LasCasas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1543.00.00,1543.00.00,136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6185,2023-08-16,2023,Provoked,PORTUGAL,Norte,9 nm off Vila do Conde,Fishing,male,M,35,...,N,19h30,Blue shark,"Portugese Resident, 8/17/2023",NaN,NaN,NaN,NaN,NaN,NaN
6186,2023-08-16,2023,Unprovoked,SPAIN,Valencia,Rabdells Beach,Wading,male,M,NaN,...,N,Afternoon,Blue shark,Las Provincias,NaN,NaN,NaN,NaN,NaN,NaN
6187,NaN,2023,Unprovoked,NEW CALEDONIA,South Province,"Chateau Royal Beach, Noumea",Swimming,Brigitte Soulard,M,49,...,N,10h30,Bull shark,"Les Nouvelles Caledoinnie, 1/30/2023",NaN,NaN,NaN,NaN,NaN,NaN
6188,NaN,2023,Unprovoked,USA,Florida,"Outer Mole, Fort Zachrry Tatlor Historic Park,...",Swimming,Nicolae Cioban,M,34,...,N,14h00,NaN,"Miami Herald, 1/14/2023",NaN,NaN,NaN,NaN,NaN,NaN
6189,1836-08-19,1836,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,NaN,...,Y,NaN,NaN,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,230.0

In [6]:
shark_data['Activity'] = shark_data['Activity'].fillna("not_stated")
shark_data['Age'] = shark_data['Age'].fillna("not_stated")
shark_data['Species'] = shark_data['Species'].fillna("not_stated")
shark_data

,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,...,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number,Case Number.1,original order
0,NaN,1,Unprovoked,AUSTRALIA,New South Wales,Bondi,not_stated,male,M,not_stated,...,N,NaN,not_stated,Waverly Library,5BC-AustralianAboriginal.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,5BC-Australia,5BC,131.0
1,NaN,1000,Unprovoked,USA,Puerto Rico,Archeological site,not_stated,male,M,29,...,N,NaN,Tiger shark,P. Seigel,1000AD-PuertoRico.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1000.00.00,1000.00.00,133.0
2,NaN,1500,Unprovoked,MEXICO,NaN,NaN,not_stated,male,M,not_stated,...,N,NaN,not_stated,J. Castro,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200AD-Mexico.pdf,1200.00.00,1200.00.00,134.0
3,NaN,1518,Unprovoked,MEXICO,Yucatan,Cozumel,Swmming,A cacique (a chief),M,not_stated,...,N,NaN,not_stated,"C. Moore, GSAF",1518.04.00.R.chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R-chief.pdf,1518.04.00.R,1518.04.00.R,135.0
4,NaN,1543,Unprovoked,VENEZUELA,Magarita or Cubagua Islands,NaN,Pearl diving,Indian slave,M,not_stated,...,Y,NaN,not_stated,J. Castro,1543.00.00.R-LasCasas.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1543.00.00,1543.00.00,136.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6185,2023-08-16,2023,Provoked,PORTUGAL,Norte,9 nm off Vila do Conde,Fishing,male,M,35,...,N,19h30,Blue shark,"Portugese Resident, 8/17/2023",NaN,NaN,NaN,NaN,NaN,NaN
6186,2023-08-16,2023,Unprovoked,SPAIN,Valencia,Rabdells Beach,Wading,male,M,not_stated,...,N,Afternoon,Blue shark,Las Provincias,NaN,NaN,NaN,NaN,NaN,NaN
6187,NaN,2023,Unprovoked,NEW CALEDONIA,South Province,"Chateau Royal Beach, Noumea",Swimming,Brigitte Soulard,M,49,...,N,10h30,Bull shark,"Les Nouvelles Caledoinnie, 1/30/2023",NaN,NaN,NaN,NaN,NaN,NaN
6188,NaN,2023,Unprovoked,USA,Florida,"Outer Mole, Fort Zachrry Tatlor Historic Park,...",Swimming,Nicolae Cioban,M,34,...,N,14h00,not_stated,"Miami Herald, 1/14/2023",NaN,NaN,NaN,NaN,NaN,NaN
6189,1836-08-19,1836,Unprovoked,ENGLAND,Cumberland,Whitehaven,Swimming,a boy,M,not_stated,...,Y,NaN,not_stated,"C. Moore, GSAF",1835.08.19.R-Whitehaven.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,1836.08.19.R,1836.08.19.R,230.0

In [7]:
shark_data = shark_data.drop(['Date', 'Area', 'Location', 'Name', 'Time', 'Investigator or Source', 'pdf', 'href formula', 
                 'href', 'Case Number', 'Case Number.1', 'original order', 'Injury'], axis = 1)
shark_data

,Year,Type,Country,Activity,Sex,Age,Fatal (Y/N),Species
0,1,Unprovoked,AUSTRALIA,not_stated,M,not_stated,N,not_stated
1,1000,Unprovoked,USA,not_stated,M,29,N,Tiger shark
2,1500,Unprovoked,MEXICO,not_stated,M,not_stated,N,not_stated
3,1518,Unprovoked,MEXICO,Swmming,M,not_stated,N,not_stated
4,1543,Unprovoked,VENEZUELA,Pearl diving,M,not_stated,Y,not_stated
...,...,...,...,...,...,...,...,...
6185,2023,Provoked,PORTUGAL,Fishing,M,35,N,Blue shark
6186,2023,Unprovoked,SPAIN,Wading,M,not_stated,N,Blue shark
6187,2023,Unprovoked,NEW CALEDONIA,Swimming,M,49,N,Bull shark
6188,2023,Unprovoked,USA,Swimming,M,34,N,not_stated
6189,1836,Unprovoked,ENGLAND,Swimming,M,not_stated,Y,not_stated

In [8]:
shark_data.isnull().any()

Year           False
Type           False
Country        False
Activity       False
Sex            False
Age            False
Fatal (Y/N)    False
Species        False
dtype: bool

In [11]:
shark_data.loc[shark_data['Activity'].str.contains('diving'), 'Activity'] = 'Diving'
shark_data.loc[shark_data['Activity'].str.contains('Diving'), 'Activity'] = 'Diving'
shark_data.loc[shark_data['Activity'].str.contains('Dived'), 'Activity'] = 'Diving'
shark_data.loc[shark_data['Activity'].str.contains('Freediving'), 'Activity'] = 'Diving'
shark_data.loc[shark_data['Activity'].str.contains('Free-diving'), 'Activity'] = 'Diving'
shark_data.loc[shark_data['Activity'].str.contains('Freediving'), 'Activity'] = 'Diving'
shark_data.loc[shark_data['Activity'].str.contains('diver'), 'Activity'] = 'Diving'
shark_data.loc[shark_data['Activity'].str.contains('dived'), 'Activity'] = 'Diving'

shark_data.loc[shark_data['Activity'].str.contains('swimming'), 'Activity'] = 'Swimming'
shark_data.loc[shark_data['Activity'].str.contains('Swimming'), 'Activity'] = 'Swimming'
shark_data.loc[shark_data['Activity'].str.contains('Swmming'), 'Activity'] = 'Swimming'
shark_data.loc[shark_data['Activity'].str.contains('swim'), 'Activity'] = 'Swimming'
shark_data.loc[shark_data['Activity'].str.contains('Jump'), 'Activity'] = 'Swimming'
shark_data.loc[shark_data['Activity'].str.contains('Jumping'), 'Activity'] = 'Swimming'

shark_data.loc[shark_data['Activity'].str.contains('Splashing'), 'Activity'] = 'Splashing'
shark_data.loc[shark_data['Activity'].str.contains('Thrashing'), 'Activity'] = 'Splashing'

shark_data.loc[shark_data['Activity'].str.contains('Snorkeling'), 'Activity'] = 'Snorkeling'

shark_data.loc[shark_data['Activity'].str.contains('fishing'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Fishing'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Fihing'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('fish'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Fish'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Hunting'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('hunting'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('catching'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Catching'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Oystering'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Catching'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Crabbing'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Clamming'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Treading'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('prawn'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Catching'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Casting'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Angling'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('angling'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('shelling'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Lobstering'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Shrimping'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('Scalloping'), 'Activity'] = 'Fishing'
shark_data.loc[shark_data['Activity'].str.contains('pêcheur'), 'Activity'] = 'Fishing'

shark_data.loc[shark_data['Activity'].str.contains('spearfishing'), 'Activity'] = 'Spearfishing'
shark_data.loc[shark_data['Activity'].str.contains('Spearfishing'), 'Activity'] = 'Spearfishing'
shark_data.loc[shark_data['Activity'].str.contains('spear'), 'Activity'] = 'Spearfishing'
shark_data.loc[shark_data['Activity'].str.contains('Spear'), 'Activity'] = 'Spearfishing'

shark_data.loc[shark_data['Activity'].str.contains('adrift'), 'Activity'] = 'Adrift'
shark_data.loc[shark_data['Activity'].str.contains('Adrift'), 'Activity'] = 'Adrift'
shark_data.loc[shark_data['Activity'].str.contains('adrift'), 'Activity'] = 'Adrift'
shark_data.loc[shark_data['Activity'].str.contains('floating'), 'Activity'] = 'Adrift'
shark_data.loc[shark_data['Activity'].str.contains('Floating'), 'Activity'] = 'Adrift'
shark_data.loc[shark_data['Activity'].str.contains('float'), 'Activity'] = 'Adrift'

shark_data.loc[shark_data['Activity'].str.contains('Baiting'), 'Activity'] = 'Baiting_shark'
shark_data.loc[shark_data['Activity'].str.contains('baiting'), 'Activity'] = 'Baiting_shark'
shark_data.loc[shark_data['Activity'].str.contains('Chumming'), 'Activity'] = 'Baiting_shark'
shark_data.loc[shark_data['Activity'].str.contains('Feeding'), 'Activity'] = 'Baiting_shark'
shark_data.loc[shark_data['Activity'].str.contains('bait'), 'Activity'] = 'Baiting_shark'
shark_data.loc[shark_data['Activity'].str.contains('cage'), 'Activity'] = 'Baiting_shark'

shark_data.loc[shark_data['Activity'].str.contains('boarding'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('Boarding'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('Board'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('surfing'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('Surfing'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('bodysurfing'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('Body-surfing'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('surfboarding'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('Kite'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('Parasailing'), 'Activity'] = 'Surfing'
shark_data.loc[shark_data['Activity'].str.contains('Surf'), 'Activity'] = 'Surfing'

shark_data.loc[shark_data['Activity'].str.contains('ski'), 'Activity'] = 'Water_skiing'
shark_data.loc[shark_data['Activity'].str.contains('Water_skiing'), 'Activity'] = 'Water_skiing'

shark_data.loc[shark_data['Activity'].str.contains('capsized'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('boat'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Boat'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('ship'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Ship'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('wreck'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Wreck'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('bark'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Burning'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Escaping'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('collided'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('schooner'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('steamer'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('hawser'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('foundered'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('sunk'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('sank'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('canoe'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Canoe'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Canoeing'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('explosion'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Explosion'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('tank'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('torpedoed'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Explosion'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('dinghy'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Competing'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('abandoned'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('overturned'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Overturned'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Sinking'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('Sailing'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('accident'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('destroyer'), 'Activity'] = 'Boat_accident'
shark_data.loc[shark_data['Activity'].str.contains('launch'), 'Activity'] = 'Boat_accident'

shark_data.loc[shark_data['Activity'].str.contains('kayaking'), 'Activity'] = 'Kayaking'
shark_data.loc[shark_data['Activity'].str.contains('kakaking'), 'Activity'] = 'Kayaking'
shark_data.loc[shark_data['Activity'].str.contains('Kakaying'), 'Activity'] = 'Kayaking'
shark_data.loc[shark_data['Activity'].str.contains('Kayaking'), 'Activity'] = 'Kayaking'
shark_data.loc[shark_data['Activity'].str.contains('Rowing'), 'Activity'] = 'Kayaking'

shark_data.loc[shark_data['Activity'].str.contains('Paddling'), 'Activity'] = 'Paddling'
shark_data.loc[shark_data['Activity'].str.contains('paddling'), 'Activity'] = 'Paddling'
shark_data.loc[shark_data['Activity'].str.contains('Paddle'), 'Activity'] = 'Paddling'
shark_data.loc[shark_data['Activity'].str.contains('Paddleskiing'), 'Activity'] = 'Paddling'
shark_data.loc[shark_data['Activity'].str.contains('raft'), 'Activity'] = 'Paddling'
shark_data.loc[shark_data['Activity'].str.contains('SUP'), 'Activity'] = 'Paddling'

shark_data.loc[shark_data['Activity'].str.contains('overboard'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('fell'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Fell'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('fell'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('overboard'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Washed'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Washing'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Washed'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Knocked'), 'Activity'] = 'Falling_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Swept'), 'Activity'] = 'Falling_in_water'

shark_data.loc[shark_data['Activity'].str.contains('Playing'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Playing_in_water'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Crouching'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Exercising'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Kneeling'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('waist'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Lying'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Riding'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Sittting'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Sitting'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Sittting'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Resting'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Walking'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Resting'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Ran'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Stamding'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Squatting'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('jackets'), 'Activity'] = 'Playing_in_water'
shark_data.loc[shark_data['Activity'].str.contains('Towing'), 'Activity'] = 'Playing_in_water'

shark_data.loc[shark_data['Activity'].str.contains('Filming'), 'Activity'] = 'Filming'
shark_data.loc[shark_data['Activity'].str.contains('filming'), 'Activity'] = 'Filming'
shark_data.loc[shark_data['Activity'].str.contains('Photographing'), 'Activity'] = 'Filming'
shark_data.loc[shark_data['Activity'].str.contains('photography'), 'Activity'] = 'Filming'

shark_data.loc[shark_data['Activity'].str.contains('Attempting'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Bitten'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Bathing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('bathing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Chumming'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Feeding'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Killing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Shooting'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Touching'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Baiting'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Batin'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Netting'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Attempted'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Attacked'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('netting'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Bending'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Hooking'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('hooking'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('hooked'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Harassing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Wading'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('wading'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Trying'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Dragging'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Reaching'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Restraining'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('pursuing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Dangling'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Trailing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Standing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Crossing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Gaffing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Pulling'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('foot'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Hand'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Defecating'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('shot'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('exercising'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('teeth'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('finning'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Finning'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Hauling'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('land'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Grabbing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('holding'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Petting'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Picking'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Moving'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Grabbed'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Meshing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('hoisted'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Sculling'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Teasing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Slapped'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Stuffing'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('netters'), 'Activity'] = 'Wrong_decision'
shark_data.loc[shark_data['Activity'].str.contains('Holding'), 'Activity'] = 'Wrong_decision'

shark_data.loc[shark_data['Activity'].str.contains('Disaster'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('disaster'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('Aircaft'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('aircraft'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('balloon'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('transport'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('Parachuted'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('Plane'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('plane'), 'Activity'] = 'Air/Sea_Disaster'
shark_data.loc[shark_data['Activity'].str.contains('Jet'), 'Activity'] = 'Air/Sea_Disaster'

shark_data.loc[shark_data['Activity'].str.contains('Unknown'), 'Activity'] = 'Unknown'
shark_data.loc[shark_data['Activity'].str.contains('Hilo'), 'Activity'] = 'Unknown'
shark_data.loc[shark_data['Activity'].str.contains('Body'), 'Activity'] = 'Unknown'
shark_data.loc[shark_data['Activity'].str.contains('not_stated'), 'Activity'] = 'Unknown'
shark_data.loc[shark_data['Activity'].str.contains('beach'), 'Activity'] = 'Unknown'
shark_data.loc[shark_data['Activity'] == '.', 'Activity'] = 'Unknown'

shark_data.loc[shark_data['Activity'].str.contains('Collecting'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Gathering'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Conducting'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Measuring'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Rescue'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Rescuing'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('rescue'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Reviving'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('tagging'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Tagging'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Removing'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('research'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Research'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Searching'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('Aquarium'), 'Activity'] = 'Research/Rescue'
shark_data.loc[shark_data['Activity'].str.contains('aid'), 'Activity'] = 'Research/Rescue'

shark_data.loc[shark_data['Activity'].str.contains('Murder'), 'Activity'] = 'Murder'
shark_data.loc[shark_data['Activity'].str.contains('Murdering'), 'Activity'] = 'Murder'
shark_data.loc[shark_data['Activity'].str.contains('Captured'), 'Activity'] = 'Murder'
shark_data.loc[shark_data['Activity'].str.contains('Pushed'), 'Activity'] = 'Murder'
shark_data.loc[shark_data['Activity'].str.contains('Suicide'), 'Activity'] = 'Murder'

shark_data.loc[shark_data['Activity'].str.contains('Lifeguard'), 'Activity'] = 'Lifeguard_Activity'
shark_data.loc[shark_data['Activity'].str.contains('Lifesaving'), 'Activity'] = 'Lifeguard_Activity'

shark_data.loc[shark_data['Activity'].str.contains('Jackass'), 'Activity'] = 'Jackass'

shark_data

,Year,Type,Country,Activity,Sex,Age,Fatal (Y/N),Species
0,1,Unprovoked,AUSTRALIA,Unknown,M,not_stated,N,not_stated
1,1000,Unprovoked,USA,Unknown,M,29,N,Tiger shark
2,1500,Unprovoked,MEXICO,Unknown,M,not_stated,N,not_stated
3,1518,Unprovoked,MEXICO,Swimming,M,not_stated,N,not_stated
4,1543,Unprovoked,VENEZUELA,Diving,M,not_stated,Y,not_stated
...,...,...,...,...,...,...,...,...
6185,2023,Provoked,PORTUGAL,Fishing,M,35,N,Blue shark
6186,2023,Unprovoked,SPAIN,Wrong_decision,M,not_stated,N,Blue shark
6187,2023,Unprovoked,NEW CALEDONIA,Swimming,M,49,N,Bull shark
6188,2023,Unprovoked,USA,Swimming,M,34,N,not_stated
6189,1836,Unprovoked,ENGLAND,Swimming,M,not_stated,Y,not_stated

In [12]:
shark_data['Activity'].unique()

array(['Unknown', 'Swimming', 'Diving', 'Boat_accident', 'Wrong_decision',
       'Falling_in_water', 'Fishing', 'Murder', 'Surfing', 'Paddling',
       'Adrift', 'Kayaking', 'Playing_in_water', 'Splashing',
       'Research/Rescue', 'Filming', 'Water_skiing', 'Lifeguard_Activity',
       'Snorkeling', 'Jackass'], dtype=object)

In [13]:
shark_data.loc[shark_data['Species'].str.contains('hammerhead'), 'Species'] = 'Hammerhead'
shark_data.loc[shark_data['Species'].str.contains('Hammerhead'), 'Species'] = 'Hammerhead'
shark_data.loc[shark_data['Species'].str.contains('Tiger'), 'Species'] = 'Tiger'
shark_data.loc[shark_data['Species'].str.contains('tiger'), 'Species'] = 'Tiger'
shark_data.loc[shark_data['Species'].str.contains('Wfite'), 'Species'] = 'White'
shark_data.loc[shark_data['Species'].str.contains('White'), 'Species'] = 'White'
shark_data.loc[shark_data['Species'].str.contains('white'), 'Species'] = 'White'
shark_data.loc[shark_data['Species'].str.contains('white'), 'Species'] = 'White'
shark_data.loc[shark_data['Species'].str.contains('Bull'), 'Species'] = 'Bull'
shark_data.loc[shark_data['Species'].str.contains('Zambesi'), 'Species'] = 'Bull'
shark_data.loc[shark_data['Species'].str.contains('Zambezi'), 'Species'] = 'Bull'
shark_data.loc[shark_data['Species'].str.contains('Caribbean'), 'Species'] = 'Caribbean_Reef'
shark_data.loc[shark_data['Species'].str.contains('caribbean'), 'Species'] = 'Caribbean_Reef'
shark_data.loc[shark_data['Species'].str.contains('Grey'), 'Species'] = 'Grey_Reef'
shark_data.loc[shark_data['Species'].str.contains('grey'), 'Species'] = 'Grey_Reef'
shark_data.loc[shark_data['Species'].str.contains('sand'), 'Species'] = 'Sand_Tiger'
shark_data.loc[shark_data['Species'].str.contains('Sand'), 'Species'] = 'Sand_Tiger'
shark_data.loc[shark_data['Species'].str.contains('Sandtiger'), 'Species'] = 'Sand_Tiger'
shark_data.loc[shark_data['Species'].str.contains('whitetip'), 'Species'] = 'Whitetip'
shark_data.loc[shark_data['Species'].str.contains('spinner'), 'Species'] = 'Spinner'
shark_data.loc[shark_data['Species'].str.contains('carpet'), 'Species'] = 'Carpet'
shark_data.loc[shark_data['Species'].str.contains('Carpet'), 'Species'] = 'Carpet'
shark_data.loc[shark_data['Species'].str.contains('sevengill'), 'Species'] = 'Sevengill'
shark_data.loc[shark_data['Species'].str.contains('Sevengill'), 'Species'] = 'Sevengill'
shark_data.loc[shark_data['Species'].str.contains('7-gill'), 'Species'] = 'Sevengill'
shark_data.loc[shark_data['Species'].str.contains('Seven-gill'), 'Species'] = 'Sevengill'
shark_data.loc[shark_data['Species'].str.contains('Broadnose'), 'Species'] = 'Sevengill' 
shark_data.loc[shark_data['Species'].str.contains('catshark'), 'Species'] = 'Catshark'
shark_data.loc[shark_data['Species'].str.contains('Catshark'), 'Species'] = 'Catshark'
shark_data.loc[shark_data['Species'].str.contains('bull'), 'Species'] = 'Bull'
shark_data.loc[shark_data['Species'].str.contains('Bull'), 'Species'] = 'Bull'
shark_data.loc[shark_data['Species'].str.contains('Bu.ll'), 'Species'] = 'Bull'
shark_data.loc[shark_data['Species'].str.contains('blacktip'), 'Species'] = 'Blacktip'
shark_data.loc[shark_data['Species'].str.contains('Blacktip'), 'Species'] = 'Blacktip'
shark_data.loc[shark_data['Species'].str.contains('copper'), 'Species'] = 'Copper'
shark_data.loc[shark_data['Species'].str.contains('Copper'), 'Species'] = 'Copper'
shark_data.loc[shark_data['Species'].str.contains('gaffed'), 'Species'] = 'Copper'
shark_data.loc[shark_data['Species'].str.contains('albimarginatus'), 'Species'] = 'Silvertip'
shark_data.loc[shark_data['Species'].str.contains('silvertip'), 'Species'] = 'Silvertip'
shark_data.loc[shark_data['Species'].str.contains('Silvertip'), 'Species'] = 'Silvertip'
shark_data.loc[shark_data['Species'].str.contains('blackfin'), 'Species'] = 'Blackfin'
shark_data.loc[shark_data['Species'].str.contains('maco'), 'Species'] = 'Mako'
shark_data.loc[shark_data['Species'].str.contains('Maco'), 'Species'] = 'Mako'
shark_data.loc[shark_data['Species'].str.contains('mako'), 'Species'] = 'Mako'
shark_data.loc[shark_data['Species'].str.contains('Mako'), 'Species'] = 'Mako'
shark_data.loc[shark_data['Species'].str.contains('blue'), 'Species'] = 'Blue'
shark_data.loc[shark_data['Species'].str.contains('Blue'), 'Species'] = 'Blue'
shark_data.loc[shark_data['Species'].str.contains('silky'), 'Species'] = 'Silky'
shark_data.loc[shark_data['Species'].str.contains('Silky'), 'Species'] = 'Silky'
shark_data.loc[shark_data['Species'].str.contains('thresher'), 'Species'] = 'Thresher'
shark_data.loc[shark_data['Species'].str.contains('Thresher'), 'Species'] = 'Thresher'
shark_data.loc[shark_data['Species'].str.contains('dusky'), 'Species'] = 'Dusky'
shark_data.loc[shark_data['Species'].str.contains('dogfish'), 'Species'] = 'Dogfish'
shark_data.loc[shark_data['Species'].str.contains('Leopard'), 'Species'] = 'Leopard'
shark_data.loc[shark_data['Species'].str.contains('banjo'), 'Species'] = 'Banjo'
shark_data.loc[shark_data['Species'].str.contains('Banjo'), 'Species'] = 'Banjo'
shark_data.loc[shark_data['Species'].str.contains('whaler'), 'Species'] = 'Whale'
shark_data.loc[shark_data['Species'].str.contains('whale'), 'Species'] = 'Whale'
shark_data.loc[shark_data['Species'].str.contains('Whale'), 'Species'] = 'Whale'
shark_data.loc[shark_data['Species'].str.contains('While'), 'Species'] = 'Whale'
shark_data.loc[shark_data['Species'].str.contains('lemon'), 'Species'] = 'Lemon'
shark_data.loc[shark_data['Species'].str.contains('Lemon'), 'Species'] = 'Lemon'
shark_data.loc[shark_data['Species'].str.contains('nurse'), 'Species'] = 'Nurse'
shark_data.loc[shark_data['Species'].str.contains('Nurse'), 'Species'] = 'Nurse'
shark_data.loc[shark_data['Species'].str.contains('Angel'), 'Species'] = 'Angel'
shark_data.loc[shark_data['Species'].str.contains('Baskin'), 'Species'] = 'Baskin'
shark_data.loc[shark_data['Species'].str.contains('Wobbegongs'), 'Species'] = 'Wobbegong'
shark_data.loc[shark_data['Species'].str.contains('Wobbegong'), 'Species'] = 'Wobbegong'
shark_data.loc[shark_data['Species'].str.contains('Raggedtooth'), 'Species'] = 'Raggedtooth'
shark_data.loc[shark_data['Species'].str.contains('Leopard'), 'Species'] = 'Leopard'
shark_data.loc[shark_data['Species'].str.contains('Horn'), 'Species'] = 'Horn'
shark_data.loc[shark_data['Species'].str.contains('Goblin'), 'Species'] = 'Goblin'
shark_data.loc[shark_data['Species'].str.contains('Bonita'), 'Species'] = 'Bonito'
shark_data.loc[shark_data['Species'].str.contains('Coockiecutter'), 'Species'] = 'Cookiecutter'
shark_data.loc[shark_data['Species'].str.contains('cookiecutter'), 'Species'] = 'Cookiecutter'
shark_data.loc[shark_data['Species'].str.contains('Dusky'), 'Species'] = 'Dusky'
shark_data.loc[shark_data['Species'].str.contains('Epaulette'), 'Species'] = 'Epaulette'
shark_data.loc[shark_data['Species'].str.contains('Galapagos'), 'Species'] = 'Galapagos'
shark_data.loc[shark_data['Species'].str.contains('Salmon'), 'Species'] = 'Salmon'
shark_data.loc[shark_data['Species'].str.contains('Porbeagle'), 'Species'] = 'Porbeagle'
shark_data.loc[shark_data['Species'].str.contains('Shovelnose'), 'Species'] = 'Shovelnose'
shark_data.loc[shark_data['Species'].str.contains('gummy'), 'Species'] = 'Gummy'
shark_data.loc[shark_data['Species'].str.contains('Reef'), 'Species'] = 'Reef'
shark_data.loc[shark_data['Species'].str.contains('Spurdog'), 'Species'] = 'Spurdog'
shark_data.loc[shark_data['Species'].str.contains('Spinner'), 'Species'] = 'Spinner'
shark_data.loc[shark_data['Species'].str.contains('Tope'), 'Species'] = 'Spinner'
shark_data.loc[shark_data['Species'].str.contains('juvenile'), 'Species'] = 'Juvenile'
shark_data.loc[shark_data['Species'].str.contains('Juvenile'), 'Species'] = 'Juvenile'
shark_data.loc[shark_data['Species'].str.contains('pup'), 'Species'] = 'Juvenile'

shark_data.loc[shark_data['Species'].str.contains('School'), 'Species'] = 'School_of_Sharks'
shark_data.loc[shark_data['Species'].str.contains('Several'), 'Species'] = 'School_of_Sharks'
shark_data.loc[shark_data['Species'].str.contains('several'), 'Species'] = 'School_of_Sharks'

shark_data.loc[shark_data['Species'].str.contains('shark'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('Shark'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('Unidentified'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('Un-identified'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('unidentified'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('attack'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('tooth'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('fish'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('Possibly'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('m'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('cm'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('to'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('not_stated'), 'Species'] = 'Unidentified'
shark_data.loc[shark_data['Species'].str.contains('Unknown'), 'Species'] = 'Unidentified'

shark_data.loc[shark_data['Species'].str.contains('injury'), 'Species'] = 'Non-shark'
shark_data.loc[shark_data['Species'].str.contains('Injury'), 'Species'] = 'Non-shark'
shark_data.loc[shark_data['Species'].str.contains('maculpinnis'), 'Species'] = 'Non-shark'
shark_data.loc[shark_data['Species'].str.contains('gangeticus'), 'Species'] = 'Non-shark'



shark_data.loc[shark_data['Species'].str.contains('involvement'), 'Species'] = 'Possibly_not_shark'
shark_data

,Year,Type,Country,Activity,Sex,Age,Fatal (Y/N),Species
0,1,Unprovoked,AUSTRALIA,Unknown,M,not_stated,N,Unidentified
1,1000,Unprovoked,USA,Unknown,M,29,N,Tiger
2,1500,Unprovoked,MEXICO,Unknown,M,not_stated,N,Unidentified
3,1518,Unprovoked,MEXICO,Swimming,M,not_stated,N,Unidentified
4,1543,Unprovoked,VENEZUELA,Diving,M,not_stated,Y,Unidentified
...,...,...,...,...,...,...,...,...
6185,2023,Provoked,PORTUGAL,Fishing,M,35,N,Blue
6186,2023,Unprovoked,SPAIN,Wrong_decision,M,not_stated,N,Blue
6187,2023,Unprovoked,NEW CALEDONIA,Swimming,M,49,N,Bull
6188,2023,Unprovoked,USA,Swimming,M,34,N,Unidentified
6189,1836,Unprovoked,ENGLAND,Swimming,M,not_stated,Y,Unidentified

In [ ]:
shark_data['Species'].unique()

In [ ]:
shark_data.loc[shark_data['Type'].str.contains('Sea'), 'Type'] = 'Questionable'
shark_data.loc[shark_data['Type'].str.contains('Watercraft'), 'Type'] = 'Questionable'
shark_data

In [ ]:
shark_data['Type'].unique()

In [ ]:
shark_data['Sex'].unique()

In [ ]:
shark_data.to_excel("shark_data_activities_clean_1.xlsx")

In [ ]:
#pull data of attacks per activity and per provoke-not provoked
#plot into chart

In [ ]:
#pull data of most and least fatal activity
#plot into chart

In [ ]:
#pull data of most common activity that provoked attacks
#plot data